# Server
server:
  port: 8081

spring:
  # Datasource
  liquibase:
    change-log: classpath:changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  # Kafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  # Redis cache
  cache:
    redis:
      time-to-live: 10000S
# Topics
kafka:
  topic:
    registrations:
      name: registration_events
# Tokens
token:
  jwt-token-expiration-time-minutes: 20
  refresh-token-expiration-time-days: 31
  confirmation-token-expiration-time-minutes: 15
  jwt-token-secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566b5970
