# Server
server:
  port: 8081

# Datasource
spring:
  liquibase:
    change-log: classpath:changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

# Jwt
jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566b5970
  expiration-time-hours: 24
